/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    firms: Firm;
    challenges: Challenge;
    promos: Promo;
    reviews: Review;
    'news-posts': NewsPost;
    'rule-changes': RuleChange;
    platforms: Platform;
    countries: Country;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    firms: FirmsSelect<false> | FirmsSelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    promos: PromosSelect<false> | PromosSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'news-posts': NewsPostsSelect<false> | NewsPostsSelect<true>;
    'rule-changes': RuleChangesSelect<false> | RuleChangesSelect<true>;
    platforms: PlatformsSelect<false> | PlatformsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'hi' | 'es') | ('en' | 'hi' | 'es')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'hi' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firms".
 */
export interface Firm {
  id: number;
  name: string;
  slug: string;
  listingType: 'listed' | 'unlisted' | 'delisted';
  firmTypes: ('cfd' | 'futures' | 'crypto' | 'options' | 'stocks')[];
  /**
   * ISO2 of HQ/jurisdiction
   */
  country?: string | null;
  currency?: string | null;
  dateEstablished?: string | null;
  websiteUrl?: string | null;
  affiliateUrl?: string | null;
  trustpilotUrl?: string | null;
  discordUrl?: string | null;
  logo?: (number | null) | Media;
  /**
   * CSS color, e.g. #121355
   */
  logoBackgroundColor?: string | null;
  maxAllocation?: number | null;
  programTypes?: ('instant' | '1-step' | '2-step' | '3-step')[] | null;
  assets?: ('fx' | 'indices' | 'metals' | 'energy' | 'crypto' | 'stocks' | 'other-commodities')[] | null;
  platforms?: (number | Platform)[] | null;
  reviewScore?: number | null;
  reviewsCount?: number | null;
  trustPilotScore?: number | null;
  /**
   * Weekly tracked scores — powers the trend chart (our moat)
   */
  trustpilotHistory?:
    | {
        date: string;
        score: number;
        id?: string | null;
      }[]
    | null;
  likesCount?: number | null;
  verdict?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  rulesSummary?: {
    drawdownType?: ('static' | 'trailing-eod' | 'trailing-intraday' | 'hybrid') | null;
    /**
     * null = no consistency rule
     */
    consistencyRulePct?: number | null;
    newsTradingAllowed?: boolean | null;
    eaAllowed?: boolean | null;
    minTradingDays?: number | null;
  };
  payout?: {
    methods?: ('crypto' | 'bank-transfer' | 'wise' | 'paypal' | 'other')[] | null;
    /**
     * e.g. "bi-weekly", "on-demand after 14d"
     */
    frequency?: string | null;
    profitSplitPct?: number | null;
    /**
     * Tracked from community proofs
     */
    avgPayoutDays?: number | null;
  };
  /**
   * Editorial pros & cons shown on the profile page
   */
  prosCons?: {
    pros?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    cons?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Editorial subscores powering the profile breakdown (0–5)
   */
  scores?: {
    pricingValue?: number | null;
    rulesFairness?: number | null;
    payoutReliability?: number | null;
    support?: number | null;
    platforms?: number | null;
  };
  restrictedCountries?: (number | Country)[] | null;
  underReview?: boolean | null;
  underReviewNote?: string | null;
  /**
   * Only set above "none" when a dated, publicly verifiable source exists in riskEvents.
   */
  riskStatus?: ('none' | 'watch' | 'ceased' | 'regulatory' | 'rebranded') | null;
  /**
   * One factual sentence: what happened and when. No characterisation.
   */
  riskSummary?: string | null;
  /**
   * Dated public record. Each row REQUIRES a source URL.
   */
  riskEvents?:
    | {
        date: string;
        event: string;
        /**
         * Public, verifiable URL (regulator, court, or firm announcement).
         */
        sourceUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-set on every save
   */
  lastVerifiedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Only enable once data-density threshold met (verdict + challenges + rules)
     */
    indexable?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms".
 */
export interface Platform {
  id: number;
  name: string;
  slug: string;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  iso2: string;
  flagEmoji?: string | null;
  /**
   * Local payment rails, payout methods that work here — for /countries pages
   */
  paymentNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: number;
  firm: number | Firm;
  /**
   * e.g. "Stellar 2-Step 100K"
   */
  name: string;
  steps: 'instant' | '1-step' | '2-step' | '3-step';
  accountSize: number;
  price: number;
  currency?: string | null;
  profitTargets?:
    | {
        phase: number;
        targetPct: number;
        id?: string | null;
      }[]
    | null;
  maxDailyLossPct?: number | null;
  maxTotalDrawdownPct?: number | null;
  drawdownType?: ('static' | 'trailing-eod' | 'trailing-intraday' | 'hybrid') | null;
  profitSplitPct?: number | null;
  refundableFee?: boolean | null;
  /**
   * Fine-print note rendered as a footnote on the pricing table, e.g. staged fees where total cost differs from the entry price
   */
  feeNote?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos".
 */
export interface Promo {
  id: number;
  firm: number | Firm;
  code: string;
  description?: string | null;
  discountPct?: number | null;
  exclusive?: boolean | null;
  endDate?: string | null;
  active?: boolean | null;
  /**
   * e.g. free account on payout
   */
  extraPerks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  firm: number | Firm;
  rating: number;
  title: string;
  body: string;
  authorName: string;
  verified?: boolean | null;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-posts".
 */
export interface NewsPost {
  id: number;
  title: string;
  slug: string;
  type: 'launch' | 'collapse' | 'rule-change' | 'update' | 'industry';
  firm?: (number | null) | Firm;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Per-firm rule-change timeline — unique content moat, renders on profiles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-changes".
 */
export interface RuleChange {
  id: number;
  firm: number | Firm;
  date: string;
  summary: string;
  details?: string | null;
  /**
   * URL or "official Discord" etc.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'firms';
        value: number | Firm;
      } | null)
    | ({
        relationTo: 'challenges';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'promos';
        value: number | Promo;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'news-posts';
        value: number | NewsPost;
      } | null)
    | ({
        relationTo: 'rule-changes';
        value: number | RuleChange;
      } | null)
    | ({
        relationTo: 'platforms';
        value: number | Platform;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firms_select".
 */
export interface FirmsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  listingType?: T;
  firmTypes?: T;
  country?: T;
  currency?: T;
  dateEstablished?: T;
  websiteUrl?: T;
  affiliateUrl?: T;
  trustpilotUrl?: T;
  discordUrl?: T;
  logo?: T;
  logoBackgroundColor?: T;
  maxAllocation?: T;
  programTypes?: T;
  assets?: T;
  platforms?: T;
  reviewScore?: T;
  reviewsCount?: T;
  trustPilotScore?: T;
  trustpilotHistory?:
    | T
    | {
        date?: T;
        score?: T;
        id?: T;
      };
  likesCount?: T;
  verdict?: T;
  rulesSummary?:
    | T
    | {
        drawdownType?: T;
        consistencyRulePct?: T;
        newsTradingAllowed?: T;
        eaAllowed?: T;
        minTradingDays?: T;
      };
  payout?:
    | T
    | {
        methods?: T;
        frequency?: T;
        profitSplitPct?: T;
        avgPayoutDays?: T;
      };
  prosCons?:
    | T
    | {
        pros?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cons?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  scores?:
    | T
    | {
        pricingValue?: T;
        rulesFairness?: T;
        payoutReliability?: T;
        support?: T;
        platforms?: T;
      };
  restrictedCountries?: T;
  underReview?: T;
  underReviewNote?: T;
  riskStatus?: T;
  riskSummary?: T;
  riskEvents?:
    | T
    | {
        date?: T;
        event?: T;
        sourceUrl?: T;
        id?: T;
      };
  lastVerifiedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        indexable?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  firm?: T;
  name?: T;
  steps?: T;
  accountSize?: T;
  price?: T;
  currency?: T;
  profitTargets?:
    | T
    | {
        phase?: T;
        targetPct?: T;
        id?: T;
      };
  maxDailyLossPct?: T;
  maxTotalDrawdownPct?: T;
  drawdownType?: T;
  profitSplitPct?: T;
  refundableFee?: T;
  feeNote?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos_select".
 */
export interface PromosSelect<T extends boolean = true> {
  firm?: T;
  code?: T;
  description?: T;
  discountPct?: T;
  exclusive?: T;
  endDate?: T;
  active?: T;
  extraPerks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  firm?: T;
  rating?: T;
  title?: T;
  body?: T;
  authorName?: T;
  verified?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-posts_select".
 */
export interface NewsPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  firm?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rule-changes_select".
 */
export interface RuleChangesSelect<T extends boolean = true> {
  firm?: T;
  date?: T;
  summary?: T;
  details?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platforms_select".
 */
export interface PlatformsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  iso2?: T;
  flagEmoji?: T;
  paymentNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}